### ISSUE TITLE
Action bar showing below status bar

### ISSUE THREAD

**Issue by prashantsaini1** [manumaticx/NavigationDrawer-Demo#1]
I tried the demo app on Android 5.1 and Android 6 and it produces the same result showing the action bar below status bar. Please advise me how to achieve the desired results as you have shown in gif  screenshot on this page https://github.com/manumaticx/NavigationDrawer-Demo.

I have not applied the theme in tiapp.xml file because you are already using NoActionBar theme in index.tss
![screenshot_20161025-123426](https://cloud.githubusercontent.com/assets/20779626/19676080/d33da738-9aaf-11e6-86ea-7c3e19b7bf2a.png)

Note: In screenshot (captured with drawer opened slightly), ignore the circle on right edge, it's ES File explorer widget.

**Comment by prashantsaini1** [comment]
I just found out that this issue is happening since version 1.4.2 and this issue is not in last version I tested which is 1.3.6. I think you are not adding androidPaddingTop:24dp in version 1.4.2.

See attached image for drawer_layout.xml file content (right one is of 1.3.6 and left one is 1.4.2)
![screen shot 2016-10-25 at 5 27 45 pm](https://cloud.githubusercontent.com/assets/20779626/19685152/acc4af42-9ad8-11e6-9d35-46e065c8f61e.png)

**Comment by manumaticx** [comment]
Hi @prashantsaini1 

when building this demo app, make sure it packages the locale module, not a globally installed version. That padding is defined for this module only.

https://github.com/manumaticx/NavigationDrawer-Demo/blob/master/modules/android/com.tripvi.drawerlayout/1.4.2/platform/android/res/layout/drawer_main.xml#L25
